#!/bin/bash
#SBATCH --time=0-03:00:00
#SBATCH -N 1
#SBATCH -C gpu
#SBATCH -o log.out
#SBATCH -e log.err
#SBATCH -J nmt

module load cuda

export ABS=$PWD
export OUT_DIR=/home/mktran/bso/bpeComparison/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/mktran/cudnn/lib64/

mkdir -p $MDL_DIR
. /home/mktran/torch/install/bin/torch-activate

th $ABS/pretrain.lua -gpuid 1 -rnn_size 1024 -word_vec_size 1024 -learning_rate 1
